[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.16.0", default-features = false }
embedded-graphics = "0.7"
profont = "0.6"
spin = "0.9"
uart_16550 = "0.2"
x86_64 = "0.14"
ps2 = "0.2"
phf = { version = "0.11", default-features = false, features = ["macros"] }
