[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { version = "0.16.0", features = ["exts"] }
uefi-services = "0.13"
# linked_list_allocator = "0.10"
log = "0.4"
embedded-graphics = "0.7"
